import type { ExInput } from "./seed-types";

export type LessonDef = {
  slug: string;
  title: string;
  description: string;
  xpReward?: number;
  estimatedMin?: number;
  conceptKeys?: string[];
  exercises: ExInput[];
};

export type UnitDef = {
  slug: string;
  title: string;
  description: string;
  stage: number;
  lessons: LessonDef[];
};

export const UNITS: UnitDef[] = [
  {
    slug: "letters-i",
    title: "Letters I",
    description: "Meet your first Arabic letters: shapes that look nothing alike.",
    stage: 1,
    lessons: [
      {
        slug: "ba-and-mim",
        title: "ب and م",
        description: "Two clear shapes: ba (b) and mim (m).",
        conceptKeys: ["letter:ba", "letter:mim", "letter:ba:isolated", "letter:mim:isolated"],
        exercises: [
          { type: "intro", promptArabic: "ب", promptText: "This is ba. It makes a b sound — like the b in book.", correctAnswers: ["continue"], conceptKeys: ["letter:ba", "letter:ba:isolated"], explanation: "One dot under a boat-shaped letter → b" },
          { type: "intro", promptArabic: "م", promptText: "This is mim. It makes an m sound — like the m in moon.", correctAnswers: ["continue"], conceptKeys: ["letter:mim", "letter:mim:isolated"] },
          { type: "arabic_to_latin_mc", promptArabic: "ب", promptText: "What sound does this letter make?", correctAnswers: ["b"], distractors: ["m", "t", "n"], explanation: "ب = b  (one dot below)", conceptKeys: ["letter:ba", "letter:ba:isolated"] },
          { type: "arabic_to_latin_mc", promptArabic: "م", promptText: "What sound does this letter make?", correctAnswers: ["m"], distractors: ["b", "n", "w"], explanation: "م = m", conceptKeys: ["letter:mim", "letter:mim:isolated"] },
          { type: "latin_to_arabic_mc", promptLatin: "b", promptText: "Which letter makes the b sound?", correctAnswers: ["ب"], options: ["ب", "م", "ت", "ن"], explanation: "ب = b", conceptKeys: ["letter:ba"] },
          { type: "matching", promptText: "Match each letter to its sound", correctAnswers: ["ب=b", "م=m"], options: ["ب", "م"], tokens: ["b", "m"], conceptKeys: ["letter:ba", "letter:mim"] },
          { type: "arabic_to_latin_mc", promptArabic: "ب", promptText: "Quick check — this letter is…", correctAnswers: ["b"], distractors: ["m", "k", "l"], conceptKeys: ["letter:ba"] },
          { type: "speed_recognition", promptArabic: "م", promptText: "Tap the sound!", correctAnswers: ["m"], distractors: ["b", "n", "t"], conceptKeys: ["letter:mim"], metadata: { timeLimitMs: 8000 } },
        ],
      },
      {
        slug: "ta-and-nun",
        title: "ت and ن",
        description: "Add ta (t) and nun (n) to your toolkit.",
        conceptKeys: ["letter:ta", "letter:nun"],
        exercises: [
          { type: "intro", promptArabic: "ت", promptText: "This is ta. Two dots above — sound: t.", correctAnswers: ["continue"], conceptKeys: ["letter:ta"], explanation: "Same boat shape as ب, but two dots on top." },
          { type: "intro", promptArabic: "ن", promptText: "This is nun. One dot above a curved shape — sound: n.", correctAnswers: ["continue"], conceptKeys: ["letter:nun"] },
          { type: "similar_letter", promptText: "Which letter makes the t sound?", promptLatin: "t", correctAnswers: ["ت"], options: ["ب", "ت", "ن"], explanation: "ت = t (two dots above). ب has one dot below.", conceptKeys: ["letter:ta", "letter:ba"] },
          { type: "arabic_to_latin_mc", promptArabic: "ت", correctAnswers: ["t"], distractors: ["b", "th", "n"], explanation: "ت = t", conceptKeys: ["letter:ta"] },
          { type: "arabic_to_latin_mc", promptArabic: "ن", correctAnswers: ["n"], distractors: ["m", "b", "t"], conceptKeys: ["letter:nun"] },
          { type: "latin_to_arabic_mc", promptLatin: "n", correctAnswers: ["ن"], options: ["م", "ن", "ب", "ت"], conceptKeys: ["letter:nun"] },
          { type: "matching", promptText: "Match the letters", correctAnswers: ["ت=t", "ن=n", "ب=b", "م=m"], options: ["ت", "ن", "ب", "م"], tokens: ["t", "n", "b", "m"], conceptKeys: ["letter:ta", "letter:nun", "letter:ba", "letter:mim"] },
          { type: "find_mistake", promptArabic: "ت", promptLatin: "b", promptText: "Is this transliteration correct?", correctAnswers: ["wrong"], explanation: "ت = t, not b. ب (one dot below) is b.", conceptKeys: ["letter:ta", "letter:ba"], metadata: { correction: "t" } },
        ],
      },
      {
        slug: "kaf-and-lam",
        title: "ك and ل",
        description: "Learn kaf (k) and lam (l).",
        conceptKeys: ["letter:kaf", "letter:lam"],
        exercises: [
          { type: "intro", promptArabic: "ك", promptText: "This is kaf — the k sound.", correctAnswers: ["continue"], conceptKeys: ["letter:kaf"] },
          { type: "intro", promptArabic: "ل", promptText: "This is lam — the l sound.", correctAnswers: ["continue"], conceptKeys: ["letter:lam"] },
          { type: "arabic_to_latin_mc", promptArabic: "ك", correctAnswers: ["k"], distractors: ["l", "q", "m"], conceptKeys: ["letter:kaf"] },
          { type: "arabic_to_latin_mc", promptArabic: "ل", correctAnswers: ["l"], distractors: ["k", "n", "b"], conceptKeys: ["letter:lam"] },
          { type: "matching", promptText: "Match all six letters so far", correctAnswers: ["ب=b", "ت=t", "م=m", "ن=n", "ك=k", "ل=l"], options: ["ب", "ت", "م", "ن", "ك", "ل"], tokens: ["b", "t", "m", "n", "k", "l"], conceptKeys: ["letter:ba", "letter:ta", "letter:mim", "letter:nun", "letter:kaf", "letter:lam"] },
          { type: "latin_to_arabic_mc", promptLatin: "k", correctAnswers: ["ك"], options: ["ك", "ل", "م", "ن"], conceptKeys: ["letter:kaf"] },
          { type: "speed_recognition", promptArabic: "ل", correctAnswers: ["l"], distractors: ["k", "n", "b"], conceptKeys: ["letter:lam"] },
        ],
      },
      {
        slug: "letters-i-review",
        title: "Letters I Review",
        description: "Lock in ب ت م ن ك ل",
        xpReward: 20,
        estimatedMin: 5,
        exercises: [
          { type: "arabic_to_latin_mc", promptArabic: "ب", correctAnswers: ["b"], distractors: ["t", "n", "m"], conceptKeys: ["letter:ba"] },
          { type: "arabic_to_latin_mc", promptArabic: "ت", correctAnswers: ["t"], distractors: ["b", "th", "n"], conceptKeys: ["letter:ta"] },
          { type: "similar_letter", promptText: "Find b", promptLatin: "b", correctAnswers: ["ب"], options: ["ب", "ت", "ن"], explanation: "ب has one dot below. ت has two above.", conceptKeys: ["letter:ba", "letter:ta"] },
          { type: "matching", promptText: "Match quickly", correctAnswers: ["ك=k", "ل=l", "م=m", "ن=n"], options: ["ك", "ل", "م", "ن"], tokens: ["k", "l", "m", "n"], conceptKeys: ["letter:kaf", "letter:lam", "letter:mim", "letter:nun"] },
          { type: "latin_to_arabic_mc", promptLatin: "m", correctAnswers: ["م"], options: ["م", "ن", "ب", "ل"], conceptKeys: ["letter:mim"] },
          { type: "find_mistake", promptArabic: "ن", promptLatin: "m", promptText: "Correct transliteration?", correctAnswers: ["wrong"], explanation: "ن = n. م = m.", conceptKeys: ["letter:nun", "letter:mim"], metadata: { correction: "n" } },
          { type: "speed_recognition", promptArabic: "ك", correctAnswers: ["k"], distractors: ["l", "q", "t"], conceptKeys: ["letter:kaf"] },
        ],
      },
    ],
  },
  {
    slug: "letters-ii",
    title: "Letters II",
    description: "Letter families — same shape, different dots.",
    stage: 2,
    lessons: [
      {
        slug: "ba-family",
        title: "The ب ت ث family",
        description: "One shape, different dots: b, t, th.",
        xpReward: 18,
        estimatedMin: 5,
        conceptKeys: ["letter:tha", "letter:ba", "letter:ta"],
        exercises: [
          { type: "intro", promptArabic: "ب ت ث", promptText: "Same boat shape. Dots tell them apart:\nب = b (1 below)\nت = t (2 above)\nث = th (3 above)", correctAnswers: ["continue"], conceptKeys: ["letter:ba", "letter:ta", "letter:tha"] },
          { type: "intro", promptArabic: "ث", promptText: "ث is tha — like th in think. Three dots on top.", correctAnswers: ["continue"], conceptKeys: ["letter:tha"] },
          { type: "similar_letter", promptText: "Which one is th?", promptLatin: "th", correctAnswers: ["ث"], options: ["ب", "ت", "ث"], explanation: "ث = th — three dots above.", conceptKeys: ["letter:tha"] },
          { type: "similar_letter", promptText: "Which one is t?", promptLatin: "t", correctAnswers: ["ت"], options: ["ب", "ت", "ث"], explanation: "ت = t — two dots above.", conceptKeys: ["letter:ta"] },
          { type: "arabic_to_latin_mc", promptArabic: "ث", correctAnswers: ["th"], distractors: ["t", "b", "sh"], explanation: "ث = th", conceptKeys: ["letter:tha"] },
          { type: "matching", promptText: "Match the family", correctAnswers: ["ب=b", "ت=t", "ث=th"], options: ["ب", "ت", "ث"], tokens: ["b", "t", "th"], conceptKeys: ["letter:ba", "letter:ta", "letter:tha"] },
          { type: "find_mistake", promptArabic: "ث", promptLatin: "t", promptText: "Is this right?", correctAnswers: ["wrong"], explanation: "ث = th (3 dots). ت = t (2 dots).", conceptKeys: ["letter:tha", "letter:ta"], metadata: { correction: "th" } },
        ],
      },
      {
        slug: "sin-shin",
        title: "س and ش",
        description: "s versus sh — watch the dots.",
        conceptKeys: ["letter:sin", "letter:shin"],
        exercises: [
          { type: "intro", promptArabic: "س", promptText: "س is sin — the s sound. No dots.", correctAnswers: ["continue"], conceptKeys: ["letter:sin"] },
          { type: "intro", promptArabic: "ش", promptText: "ش is shin — sh like in ship. Three dots on top.", correctAnswers: ["continue"], conceptKeys: ["letter:shin"] },
          { type: "similar_letter", promptText: "Which letter is sh?", promptLatin: "sh", correctAnswers: ["ش"], options: ["س", "ش", "ث"], explanation: "ش = sh (three dots). س = s (no dots).", conceptKeys: ["letter:shin", "letter:sin"] },
          { type: "arabic_to_latin_mc", promptArabic: "ش", correctAnswers: ["sh"], distractors: ["s", "th", "kh"], conceptKeys: ["letter:shin"] },
          { type: "arabic_to_latin_mc", promptArabic: "س", correctAnswers: ["s"], distractors: ["sh", "z", "th"], conceptKeys: ["letter:sin"] },
          { type: "matching", promptText: "Match", correctAnswers: ["س=s", "ش=sh"], options: ["س", "ش"], tokens: ["s", "sh"], conceptKeys: ["letter:sin", "letter:shin"] },
        ],
      },
      {
        slug: "jim-family",
        title: "ج ح خ family",
        description: "Same curved shape — j, ḥ, and kh.",
        xpReward: 18,
        conceptKeys: ["letter:jim", "letter:ha", "letter:kha"],
        exercises: [
          { type: "intro", promptArabic: "ج ح خ", promptText: "Same body shape:\nج = j (dot below)\nح = ḥ deep h (no dot)\nخ = kh (dot above)", correctAnswers: ["continue"], conceptKeys: ["letter:jim", "letter:ha", "letter:kha"] },
          { type: "intro", promptArabic: "خ", promptText: "خ = kh — like Scottish loch. Notice the single dot above.", correctAnswers: ["continue"], conceptKeys: ["letter:kha"], explanation: "خ = kh" },
          { type: "similar_letter", promptText: "Which is kh?", promptLatin: "kh", correctAnswers: ["خ"], options: ["ج", "ح", "خ"], explanation: "خ = kh — dot above. ح has no dot.", conceptKeys: ["letter:kha", "letter:ha"] },
          { type: "similar_letter", promptText: "Which is j?", promptLatin: "j", correctAnswers: ["ج"], options: ["ج", "ح", "خ"], explanation: "ج = j — dot below.", conceptKeys: ["letter:jim"] },
          { type: "arabic_to_latin_mc", promptArabic: "ح", correctAnswers: ["h"], distractors: ["kh", "j", "q"], explanation: "ح = ḥ (deep h). We accept h.", conceptKeys: ["letter:ha"] },
          { type: "arabic_to_latin_mc", promptArabic: "خ", correctAnswers: ["kh"], distractors: ["h", "j", "q"], explanation: "خ = kh (dot above)", conceptKeys: ["letter:kha"] },
          { type: "matching", promptText: "Match the family", correctAnswers: ["ج=j", "ح=h", "خ=kh"], options: ["ج", "ح", "خ"], tokens: ["j", "h", "kh"], conceptKeys: ["letter:jim", "letter:ha", "letter:kha"] },
          { type: "find_mistake", promptArabic: "ح", promptLatin: "kh", promptText: "Correct?", correctAnswers: ["wrong"], explanation: "ح has no dot = h. خ with a dot above = kh.", conceptKeys: ["letter:ha", "letter:kha"], metadata: { correction: "h" } },
        ],
      },
      {
        slug: "dal-ra-families",
        title: "د ذ and ر ز",
        description: "Two small families that do not connect forward.",
        conceptKeys: ["letter:dal", "letter:dhal", "letter:ra", "letter:zay"],
        exercises: [
          { type: "intro", promptArabic: "د ذ", promptText: "د = d\nذ = dh (like th in this) — one dot above dal.", correctAnswers: ["continue"], conceptKeys: ["letter:dal", "letter:dhal"] },
          { type: "intro", promptArabic: "ر ز", promptText: "ر = r\nز = z — one dot above ra.", correctAnswers: ["continue"], conceptKeys: ["letter:ra", "letter:zay"] },
          { type: "similar_letter", promptText: "Which is dh?", promptLatin: "dh", correctAnswers: ["ذ"], options: ["د", "ذ", "ز"], explanation: "ذ = dh — dot on dal.", conceptKeys: ["letter:dhal"] },
          { type: "similar_letter", promptText: "Which is z?", promptLatin: "z", correctAnswers: ["ز"], options: ["ر", "ز", "ذ"], explanation: "ز = z — dot on ra.", conceptKeys: ["letter:zay"] },
          { type: "matching", promptText: "Match", correctAnswers: ["د=d", "ذ=dh", "ر=r", "ز=z"], options: ["د", "ذ", "ر", "ز"], tokens: ["d", "dh", "r", "z"], conceptKeys: ["letter:dal", "letter:dhal", "letter:ra", "letter:zay"] },
          { type: "arabic_to_latin_mc", promptArabic: "ذ", correctAnswers: ["dh"], distractors: ["d", "z", "th"], conceptKeys: ["letter:dhal"] },
          { type: "arabic_to_latin_mc", promptArabic: "ز", correctAnswers: ["z"], distractors: ["r", "dh", "s"], conceptKeys: ["letter:zay"] },
        ],
      },
      {
        slug: "fa-qaf-and-more",
        title: "ف ق و ي ه",
        description: "f, q, w, y, and light h.",
        xpReward: 18,
        conceptKeys: ["letter:fa", "letter:qaf", "letter:waw", "letter:ya", "letter:ha_light"],
        exercises: [
          { type: "intro", promptArabic: "ف ق", promptText: "ف = f (one dot)\nق = q (two dots) — a deeper k from the throat.", correctAnswers: ["continue"], conceptKeys: ["letter:fa", "letter:qaf"] },
          { type: "intro", promptArabic: "و ي ه", promptText: "و = w\nي = y\nه = h", correctAnswers: ["continue"], conceptKeys: ["letter:waw", "letter:ya", "letter:ha_light"] },
          { type: "similar_letter", promptText: "Which is q?", promptLatin: "q", correctAnswers: ["ق"], options: ["ف", "ق", "ك"], explanation: "ق has two dots. ف has one. ك looks different.", conceptKeys: ["letter:qaf", "letter:fa"] },
          { type: "arabic_to_latin_mc", promptArabic: "ف", correctAnswers: ["f"], distractors: ["q", "b", "m"], conceptKeys: ["letter:fa"] },
          { type: "arabic_to_latin_mc", promptArabic: "ق", correctAnswers: ["q"], distractors: ["k", "f", "g"], conceptKeys: ["letter:qaf"] },
          { type: "matching", promptText: "Match", correctAnswers: ["و=w", "ي=y", "ه=h"], options: ["و", "ي", "ه"], tokens: ["w", "y", "h"], conceptKeys: ["letter:waw", "letter:ya", "letter:ha_light"] },
          { type: "latin_to_arabic_mc", promptLatin: "y", correctAnswers: ["ي"], options: ["ي", "و", "ن", "ب"], conceptKeys: ["letter:ya"] },
        ],
      },
    ],
  },
  {
    slug: "connected-letters",
    title: "Connected Letters",
    description: "Letters change shape when they join.",
    stage: 3,
    lessons: [
      {
        slug: "ba-forms",
        title: "ب in all positions",
        description: "Recognize ba isolated, initial, medial, and final.",
        xpReward: 18,
        estimatedMin: 5,
        conceptKeys: ["letter:ba:isolated", "letter:ba:initial", "letter:ba:medial", "letter:ba:final"],
        exercises: [
          { type: "intro", promptArabic: "ب  بـ  ـبـ  ـب", promptText: "ب changes shape depending on where it sits — but it always has one dot below and still means b.", correctAnswers: ["continue"], conceptKeys: ["letter:ba:isolated", "letter:ba:initial", "letter:ba:medial", "letter:ba:final"] },
          { type: "connected_form", promptArabic: "بـ", promptText: "This is ba at the start of a word. What sound?", correctAnswers: ["b"], distractors: ["t", "n", "m"], explanation: "Initial بـ = b", conceptKeys: ["letter:ba:initial"], metadata: { form: "initial", letter: "ba" } },
          { type: "connected_form", promptArabic: "ـبـ", promptText: "Ba in the middle — still…", correctAnswers: ["b"], distractors: ["t", "th", "n"], conceptKeys: ["letter:ba:medial"], metadata: { form: "medial", letter: "ba" } },
          { type: "connected_form", promptArabic: "ـب", promptText: "Ba at the end of a word:", correctAnswers: ["b"], distractors: ["t", "k", "l"], conceptKeys: ["letter:ba:final"], metadata: { form: "final", letter: "ba" } },
          { type: "connected_form", promptArabic: "كتب", promptText: "Look at the first letter in this sequence. What is it?", correctAnswers: ["k"], distractors: ["b", "t", "l"], explanation: "The first connected shape is ك (k).", conceptKeys: ["letter:kaf:initial"], metadata: { highlightIndex: 0, word: "كتب" } },
          { type: "similar_letter", promptText: "Which is medial ba (ـبـ)?", correctAnswers: ["ـبـ"], options: ["ـبـ", "ـتـ", "ـنـ"], explanation: "One dot below = ba, even in the middle.", conceptKeys: ["letter:ba:medial", "letter:ta:medial"] },
          { type: "arabic_to_latin_mc", promptArabic: "بـ", correctAnswers: ["b"], distractors: ["t", "n", "y"], conceptKeys: ["letter:ba:initial"] },
        ],
      },
      {
        slug: "more-connected",
        title: "Connecting ت م ن ك ل",
        description: "Practice connected forms for letters you know.",
        xpReward: 18,
        exercises: [
          { type: "connected_form", promptArabic: "تـ", promptText: "Initial form — sound?", correctAnswers: ["t"], distractors: ["b", "th", "n"], conceptKeys: ["letter:ta:initial"] },
          { type: "connected_form", promptArabic: "مـ", correctAnswers: ["m"], distractors: ["n", "b", "h"], conceptKeys: ["letter:mim:initial"] },
          { type: "connected_form", promptArabic: "ـنـ", promptText: "Medial nun:", correctAnswers: ["n"], distractors: ["b", "t", "m"], conceptKeys: ["letter:nun:medial"] },
          { type: "connected_form", promptArabic: "كـ", correctAnswers: ["k"], distractors: ["l", "m", "b"], conceptKeys: ["letter:kaf:initial"] },
          { type: "connected_form", promptArabic: "لـ", correctAnswers: ["l"], distractors: ["k", "n", "a"], conceptKeys: ["letter:lam:initial"] },
          { type: "matching", promptText: "Match connected forms", correctAnswers: ["بـ=b", "تـ=t", "مـ=m", "نـ=n"], options: ["بـ", "تـ", "مـ", "نـ"], tokens: ["b", "t", "m", "n"], conceptKeys: ["letter:ba:initial", "letter:ta:initial", "letter:mim:initial", "letter:nun:initial"] },
        ],
      },
      {
        slug: "connected-sin-shin-ya",
        title: "Connecting س ش ي",
        description: "Recognize teeth-like connected forms.",
        conceptKeys: ["letter:sin:initial", "letter:shin:initial", "letter:ya:initial", "letter:ya:medial"],
        exercises: [
          { type: "intro", promptArabic: "سـ شـ يـ", promptText: "Connected س ش ي can look similar at a glance — count the dots.", correctAnswers: ["continue"], conceptKeys: ["letter:sin:initial", "letter:shin:initial", "letter:ya:initial"] },
          { type: "connected_form", promptArabic: "سـ", correctAnswers: ["s"], distractors: ["sh", "y", "b"], conceptKeys: ["letter:sin:initial"] },
          { type: "connected_form", promptArabic: "شـ", correctAnswers: ["sh"], distractors: ["s", "th", "y"], conceptKeys: ["letter:shin:initial"] },
          { type: "connected_form", promptArabic: "يـ", correctAnswers: ["y"], distractors: ["b", "t", "n"], conceptKeys: ["letter:ya:initial"] },
          { type: "connected_form", promptArabic: "ـيـ", promptText: "Medial ya:", correctAnswers: ["y"], distractors: ["b", "t", "n"], conceptKeys: ["letter:ya:medial"] },
          { type: "similar_letter", promptText: "Which is initial shin?", correctAnswers: ["شـ"], options: ["سـ", "شـ", "يـ"], explanation: "شـ has three dots on top.", conceptKeys: ["letter:shin:initial"] },
          { type: "matching", promptText: "Match", correctAnswers: ["سـ=s", "شـ=sh", "يـ=y"], options: ["سـ", "شـ", "يـ"], tokens: ["s", "sh", "y"], conceptKeys: ["letter:sin:initial", "letter:shin:initial", "letter:ya:initial"] },
        ],
      },
    ],
  },
  {
    slug: "short-vowels",
    title: "Short Vowels",
    description: "Marks that add a, i, or u.",
    stage: 4,
    lessons: [
      {
        slug: "fatha-kasra-damma",
        title: "َ ِ ُ with ب",
        description: "Meet fatha (a), kasra (i), and damma (u).",
        xpReward: 20,
        estimatedMin: 5,
        conceptKeys: ["diacritic:fatha", "diacritic:kasra", "diacritic:damma"],
        exercises: [
          { type: "intro", promptArabic: "َ", promptText: "This small mark above a letter is fatha. It adds a short a sound.", correctAnswers: ["continue"], conceptKeys: ["diacritic:fatha"] },
          { type: "intro", promptArabic: "بَ", promptText: "ب + fatha = ba", correctAnswers: ["continue"], conceptKeys: ["diacritic:fatha", "letter:ba"] },
          { type: "intro", promptArabic: "بِ", promptText: "A mark below is kasra → short i. So بِ = bi", correctAnswers: ["continue"], conceptKeys: ["diacritic:kasra"] },
          { type: "intro", promptArabic: "بُ", promptText: "A little loop above is damma → short u. So بُ = bu", correctAnswers: ["continue"], conceptKeys: ["diacritic:damma"] },
          { type: "arabic_to_latin_mc", promptArabic: "بَ", correctAnswers: ["ba"], distractors: ["bi", "bu", "b"], explanation: "Fatha (َ) → a, so بَ = ba", conceptKeys: ["diacritic:fatha", "letter:ba"] },
          { type: "arabic_to_latin_mc", promptArabic: "بِ", correctAnswers: ["bi"], distractors: ["ba", "bu", "ib"], conceptKeys: ["diacritic:kasra"] },
          { type: "arabic_to_latin_mc", promptArabic: "بُ", correctAnswers: ["bu"], distractors: ["ba", "bi", "ub"], conceptKeys: ["diacritic:damma"] },
          { type: "matching", promptText: "Match the syllables", correctAnswers: ["بَ=ba", "بِ=bi", "بُ=bu"], options: ["بَ", "بِ", "بُ"], tokens: ["ba", "bi", "bu"], conceptKeys: ["diacritic:fatha", "diacritic:kasra", "diacritic:damma"] },
        ],
      },
      {
        slug: "reading-syllables",
        title: "Reading Syllables",
        description: "Combine known letters with short vowels.",
        xpReward: 20,
        estimatedMin: 5,
        exercises: [
          { type: "arabic_to_latin_mc", promptArabic: "كَ", correctAnswers: ["ka"], distractors: ["ki", "ku", "ak"], conceptKeys: ["letter:kaf", "diacritic:fatha"] },
          { type: "arabic_to_latin_mc", promptArabic: "تَ", correctAnswers: ["ta"], distractors: ["ba", "ti", "at"], conceptKeys: ["letter:ta", "diacritic:fatha"] },
          { type: "arabic_to_latin_mc", promptArabic: "مِ", correctAnswers: ["mi"], distractors: ["ma", "mu", "im"], conceptKeys: ["letter:mim", "diacritic:kasra"] },
          { type: "arabic_to_latin_mc", promptArabic: "نُ", correctAnswers: ["nu"], distractors: ["na", "ni", "un"], conceptKeys: ["letter:nun", "diacritic:damma"] },
          { type: "build_transliteration", promptArabic: "كَتَ", promptText: "Build the sound", correctAnswers: ["kata"], tokens: ["ka", "ta", "ba", "ma"], explanation: "كَ + تَ = kata", conceptKeys: ["letter:kaf", "letter:ta", "diacritic:fatha"] },
          { type: "build_transliteration", promptArabic: "بَتَ", correctAnswers: ["bata"], tokens: ["ba", "ta", "bi", "na"], conceptKeys: ["letter:ba", "letter:ta"] },
          { type: "type_transliteration", promptArabic: "لَمَ", promptText: "Type how this sounds", correctAnswers: ["lama"], explanation: "لَ + مَ = lama", conceptKeys: ["letter:lam", "letter:mim"] },
        ],
      },
      {
        slug: "more-syllables",
        title: "More Syllables",
        description: "Practice with س ش ف ق and mixed vowels.",
        exercises: [
          { type: "arabic_to_latin_mc", promptArabic: "سَ", correctAnswers: ["sa"], distractors: ["sha", "si", "as"], conceptKeys: ["letter:sin", "diacritic:fatha"] },
          { type: "arabic_to_latin_mc", promptArabic: "شِ", correctAnswers: ["shi"], distractors: ["sha", "shu", "si"], conceptKeys: ["letter:shin", "diacritic:kasra"] },
          { type: "arabic_to_latin_mc", promptArabic: "فُ", correctAnswers: ["fu"], distractors: ["fa", "fi", "qu"], conceptKeys: ["letter:fa", "diacritic:damma"] },
          { type: "arabic_to_latin_mc", promptArabic: "قَ", correctAnswers: ["qa"], distractors: ["ka", "qi", "fa"], conceptKeys: ["letter:qaf", "diacritic:fatha"] },
          { type: "build_transliteration", promptArabic: "سَلَ", correctAnswers: ["sala"], tokens: ["sa", "la", "sha", "ma"], conceptKeys: ["letter:sin", "letter:lam"] },
          { type: "type_transliteration", promptArabic: "شَمَ", correctAnswers: ["shama"], conceptKeys: ["letter:shin", "letter:mim"] },
          { type: "type_transliteration", promptArabic: "كُتِ", correctAnswers: ["kuti"], conceptKeys: ["letter:kaf", "letter:ta", "diacritic:damma", "diacritic:kasra"] },
        ],
      },
    ],
  },
  {
    slug: "sukun-shadda",
    title: "Sukun & Shadda",
    description: "No-vowel mark and doubled letters.",
    stage: 5,
    lessons: [
      {
        slug: "meet-sukun",
        title: "Sukun ْ",
        description: "A circle means: no vowel on this letter.",
        conceptKeys: ["diacritic:sukun"],
        exercises: [
          { type: "intro", promptArabic: "ْ", promptText: "Sukun is a small circle. It means this consonant has no short vowel.", correctAnswers: ["continue"], conceptKeys: ["diacritic:sukun"] },
          { type: "intro", promptArabic: "مِنْ", promptText: "مِنْ → min\nThe ن has sukun, so you just say n — no extra vowel.", correctAnswers: ["continue"], conceptKeys: ["diacritic:sukun", "letter:nun"] },
          { type: "arabic_to_latin_mc", promptArabic: "مِنْ", correctAnswers: ["min"], distractors: ["mina", "man", "mun"], explanation: "مِ + نْ = min", conceptKeys: ["diacritic:sukun"] },
          { type: "arabic_to_latin_mc", promptArabic: "كَتْ", correctAnswers: ["kat"], distractors: ["kata", "kit", "kut"], conceptKeys: ["diacritic:sukun", "letter:kaf", "letter:ta"] },
          { type: "build_transliteration", promptArabic: "بَتْ", correctAnswers: ["bat"], tokens: ["ba", "t", "ta", "bi"], explanation: "بَ + تْ = bat", conceptKeys: ["diacritic:sukun"] },
          { type: "type_transliteration", promptArabic: "لَمْ", correctAnswers: ["lam"], conceptKeys: ["diacritic:sukun", "letter:lam", "letter:mim"] },
          { type: "find_mistake", promptArabic: "مِنْ", promptLatin: "mina", promptText: "Is this right?", correctAnswers: ["wrong"], explanation: "Sukun on ن means no vowel after n → min, not mina.", conceptKeys: ["diacritic:sukun"], metadata: { correction: "min" } },
        ],
      },
      {
        slug: "meet-shadda",
        title: "Shadda ّ",
        description: "Double the consonant sound.",
        conceptKeys: ["diacritic:shadda"],
        exercises: [
          { type: "intro", promptArabic: "ّ", promptText: "Shadda looks like a tiny w. It means: say the consonant twice (hold/double it).", correctAnswers: ["continue"], conceptKeys: ["diacritic:shadda"] },
          { type: "intro", promptArabic: "بَبَّ", promptText: "بَبَّ → babba\nThe shadda doubles the ب.", correctAnswers: ["continue"], conceptKeys: ["diacritic:shadda"] },
          { type: "arabic_to_latin_mc", promptArabic: "كَتَّ", correctAnswers: ["katta"], distractors: ["kata", "kita", "kattu"], explanation: "شadda on ت doubles it: katta", conceptKeys: ["diacritic:shadda"] },
          { type: "arabic_to_latin_mc", promptArabic: "مُدَّ", correctAnswers: ["mudda"], distractors: ["muda", "midda", "madda"], conceptKeys: ["diacritic:shadda", "letter:mim", "letter:dal"] },
          { type: "build_transliteration", promptArabic: "سَلَّمَ", correctAnswers: ["sallama"], tokens: ["sa", "lla", "ma", "la", "sa"], explanation: "س + shadda-ل + مَ = sallama", conceptKeys: ["diacritic:shadda"] },
          { type: "type_transliteration", promptArabic: "عَلَّمَ", correctAnswers: ["allama", "ʿallama"], conceptKeys: ["diacritic:shadda", "letter:ayn"] },
          { type: "find_mistake", promptArabic: "كَتَّ", promptLatin: "kata", promptText: "Correct?", correctAnswers: ["wrong"], explanation: "Shadda doubles ت → katta, not kata.", conceptKeys: ["diacritic:shadda"], metadata: { correction: "katta" } },
        ],
      },
      {
        slug: "sukun-shadda-practice",
        title: "Sukun & Shadda Practice",
        description: "Mix both marks in short words.",
        xpReward: 20,
        exercises: [
          { type: "type_transliteration", promptArabic: "مِسْك", correctAnswers: ["misk"], conceptKeys: ["diacritic:sukun"] },
          { type: "type_transliteration", promptArabic: "شَمْس", correctAnswers: ["shams"], conceptKeys: ["diacritic:sukun", "letter:shin"] },
          { type: "type_transliteration", promptArabic: "دَرَّسَ", correctAnswers: ["darrasa"], conceptKeys: ["diacritic:shadda"] },
          { type: "build_transliteration", promptArabic: "كَتْب", correctAnswers: ["katb"], tokens: ["ka", "t", "b", "ta", "bi"], conceptKeys: ["diacritic:sukun"] },
          { type: "arabic_to_latin_mc", promptArabic: "رَبّ", correctAnswers: ["rabb"], distractors: ["rab", "ribb", "rubb"], conceptKeys: ["diacritic:shadda"] },
          { type: "type_transliteration", promptArabic: "نَمْل", correctAnswers: ["naml"], conceptKeys: ["diacritic:sukun"] },
        ],
      },
    ],
  },
  {
    slug: "long-vowels",
    title: "Long Vowels",
    description: "ا و ي as long aa, uu, and ii.",
    stage: 6,
    lessons: [
      {
        slug: "long-aa",
        title: "Long aa with ا",
        description: "Fatha + alif stretches a into aa.",
        conceptKeys: ["letter:alif", "diacritic:fatha"],
        exercises: [
          { type: "intro", promptArabic: "ا", promptText: "Alif often lengthens a preceding fatha into a long aa sound.", correctAnswers: ["continue"], conceptKeys: ["letter:alif"] },
          { type: "intro", promptArabic: "بَا", promptText: "بَا → baa (long a)", correctAnswers: ["continue"], conceptKeys: ["letter:alif", "letter:ba"] },
          { type: "arabic_to_latin_mc", promptArabic: "بَا", correctAnswers: ["baa"], distractors: ["ba", "bi", "buu"], explanation: "Fatha + ا = aa", conceptKeys: ["letter:alif"] },
          { type: "arabic_to_latin_mc", promptArabic: "كَا", correctAnswers: ["kaa"], distractors: ["ka", "kuu", "kii"], conceptKeys: ["letter:alif", "letter:kaf"] },
          { type: "build_transliteration", promptArabic: "كَتَاب", correctAnswers: ["kitaab", "kataab"], tokens: ["ki", "taa", "b", "ka", "ta", "ba"], explanation: "كِتَاب → kitaab", conceptKeys: ["letter:alif"] },
          { type: "type_transliteration", promptArabic: "بَاب", correctAnswers: ["baab"], conceptKeys: ["letter:alif", "letter:ba"] },
          { type: "find_mistake", promptArabic: "مَال", promptLatin: "mal", promptText: "Correct?", correctAnswers: ["wrong"], explanation: "ا lengthens the vowel → maal, not mal.", conceptKeys: ["letter:alif"], metadata: { correction: "maal" } },
        ],
      },
      {
        slug: "long-uu-ii",
        title: "Long uu and ii",
        description: "Damma + و and kasra + ي.",
        conceptKeys: ["letter:waw", "letter:ya"],
        exercises: [
          { type: "intro", promptArabic: "و", promptText: "After a damma, و often means long uu (not consonant w).", correctAnswers: ["continue"], conceptKeys: ["letter:waw"] },
          { type: "intro", promptArabic: "ي", promptText: "After a kasra, ي often means long ii (not consonant y).", correctAnswers: ["continue"], conceptKeys: ["letter:ya"] },
          { type: "arabic_to_latin_mc", promptArabic: "بُو", correctAnswers: ["buu"], distractors: ["bu", "baw", "bii"], conceptKeys: ["letter:waw"] },
          { type: "arabic_to_latin_mc", promptArabic: "بِي", correctAnswers: ["bii"], distractors: ["bi", "bay", "buu"], conceptKeys: ["letter:ya"] },
          { type: "type_transliteration", promptArabic: "نُور", correctAnswers: ["nuur"], conceptKeys: ["letter:waw", "letter:nun", "letter:ra"] },
          { type: "type_transliteration", promptArabic: "فِيل", correctAnswers: ["fiil"], conceptKeys: ["letter:ya", "letter:fa", "letter:lam"] },
          { type: "build_transliteration", promptArabic: "كِتَابِي", correctAnswers: ["kitaabii"], tokens: ["ki", "taa", "bii", "ka", "bi", "tii"], conceptKeys: ["letter:alif", "letter:ya"] },
          { type: "matching", promptText: "Match long vowels", correctAnswers: ["بَا=baa", "بُو=buu", "بِي=bii"], options: ["بَا", "بُو", "بِي"], tokens: ["baa", "buu", "bii"], conceptKeys: ["letter:alif", "letter:waw", "letter:ya"] },
        ],
      },
      {
        slug: "short-vs-long",
        title: "Short vs Long",
        description: "Hear the difference visually: ba vs baa.",
        xpReward: 20,
        exercises: [
          { type: "arabic_to_latin_mc", promptArabic: "بَ", correctAnswers: ["ba"], distractors: ["baa", "bi", "bu"], conceptKeys: ["diacritic:fatha"] },
          { type: "arabic_to_latin_mc", promptArabic: "بَا", correctAnswers: ["baa"], distractors: ["ba", "bi", "buu"], conceptKeys: ["letter:alif"] },
          { type: "arabic_to_latin_mc", promptArabic: "كُ", correctAnswers: ["ku"], distractors: ["kuu", "ka", "ki"], conceptKeys: ["diacritic:damma"] },
          { type: "arabic_to_latin_mc", promptArabic: "كُو", correctAnswers: ["kuu"], distractors: ["ku", "kaw", "kii"], conceptKeys: ["letter:waw"] },
          { type: "type_transliteration", promptArabic: "سَلَام", correctAnswers: ["salaam"], conceptKeys: ["letter:alif"] },
          { type: "type_transliteration", promptArabic: "مُوسَى", correctAnswers: ["muusaa", "muusa"], conceptKeys: ["letter:waw", "letter:alif_maqsurah"] },
          { type: "find_mistake", promptArabic: "نُور", promptLatin: "nur", promptText: "Correct?", correctAnswers: ["wrong"], explanation: "و after damma → nuur (long).", conceptKeys: ["letter:waw"], metadata: { correction: "nuur" } },
        ],
      },
    ],
  },
  {
    slug: "reading-words",
    title: "Reading Words",
    description: "Decode complete vowelled words.",
    stage: 7,
    lessons: [
      {
        slug: "first-words",
        title: "Your First Words",
        description: "Decode fully vowelled words — meaning optional.",
        xpReward: 25,
        estimatedMin: 6,
        exercises: [
          { type: "intro", promptArabic: "كَتَبَ", promptText: "You don't need to know what this means. Just decode: ka-ta-ba → kataba", correctAnswers: ["continue"], conceptKeys: ["letter:kaf", "letter:ta", "letter:ba"] },
          { type: "build_transliteration", promptArabic: "كَتَبَ", promptText: "Build the transliteration", correctAnswers: ["kataba"], tokens: ["ka", "ta", "ba", "bi", "ku"], explanation: "كَ تَ بَ → kataba", conceptKeys: ["letter:kaf", "letter:ta", "letter:ba", "diacritic:fatha"] },
          { type: "type_transliteration", promptArabic: "كَتَبَ", promptText: "Type the sounds", correctAnswers: ["kataba"], conceptKeys: ["letter:kaf", "letter:ta", "letter:ba"] },
          { type: "build_transliteration", promptArabic: "مَلَكَ", correctAnswers: ["malaka"], tokens: ["ma", "la", "ka", "na", "ba"], conceptKeys: ["letter:mim", "letter:lam", "letter:kaf"] },
          { type: "type_transliteration", promptArabic: "نَمَلَ", correctAnswers: ["namala"], conceptKeys: ["letter:nun", "letter:mim", "letter:lam"] },
          { type: "find_mistake", promptArabic: "كَتَبَ", promptLatin: "katiba", promptText: "Which decoding is shown — is it correct?", correctAnswers: ["wrong"], explanation: "All three vowels are fatha (a): kataba, not katiba.", conceptKeys: ["diacritic:fatha"], metadata: { correction: "kataba" } },
          { type: "type_transliteration", promptArabic: "بَتَكَ", correctAnswers: ["bataka"], conceptKeys: ["letter:ba", "letter:ta", "letter:kaf"] },
        ],
      },
      {
        slug: "everyday-shapes",
        title: "Everyday Word Shapes",
        description: "More vowelled words with letters you know.",
        xpReward: 25,
        exercises: [
          { type: "type_transliteration", promptArabic: "كِتَاب", correctAnswers: ["kitaab"], conceptKeys: ["letter:alif"] },
          { type: "type_transliteration", promptArabic: "قَلَم", correctAnswers: ["qalam"], conceptKeys: ["letter:qaf"] },
          { type: "type_transliteration", promptArabic: "مَدْرَسَة", correctAnswers: ["madrasa", "madrasah"], conceptKeys: ["diacritic:sukun", "letter:taa_marbuta"] },
          { type: "build_transliteration", promptArabic: "سَلَام", correctAnswers: ["salaam"], tokens: ["sa", "laa", "m", "sala", "lam"], conceptKeys: ["letter:alif"] },
          { type: "type_transliteration", promptArabic: "شَمْس", correctAnswers: ["shams"], conceptKeys: ["diacritic:sukun"] },
          { type: "type_transliteration", promptArabic: "نُور", correctAnswers: ["nuur"], conceptKeys: ["letter:waw"] },
          { type: "type_transliteration", promptArabic: "بَيْت", correctAnswers: ["bayt"], conceptKeys: ["diacritic:sukun", "letter:ya"] },
        ],
      },
      {
        slug: "word-challenge-easy",
        title: "Word Challenge",
        description: "Type full transliterations with mixed marks.",
        xpReward: 30,
        estimatedMin: 6,
        exercises: [
          { type: "type_transliteration", promptArabic: "مَكْتَب", correctAnswers: ["maktab"], conceptKeys: ["diacritic:sukun"] },
          { type: "type_transliteration", promptArabic: "طَالِب", correctAnswers: ["taalib", "ṭaalib"], conceptKeys: ["letter:ta_emphatic", "letter:alif"] },
          { type: "type_transliteration", promptArabic: "دَرَسَ", correctAnswers: ["darasa"], conceptKeys: ["letter:dal", "letter:ra", "letter:sin"] },
          { type: "type_transliteration", promptArabic: "كَبِير", correctAnswers: ["kabiir"], conceptKeys: ["letter:ya"] },
          { type: "type_transliteration", promptArabic: "صَغِير", correctAnswers: ["saghiir", "ṣaghiir"], conceptKeys: ["letter:sad", "letter:ghayn"] },
          { type: "build_transliteration", promptArabic: "يَكْتُبُ", correctAnswers: ["yaktubu"], tokens: ["ya", "k", "tu", "bu", "ka", "ta"], conceptKeys: ["diacritic:sukun"] },
          { type: "find_mistake", promptArabic: "كِتَاب", promptLatin: "kitab", promptText: "Correct?", correctAnswers: ["wrong"], explanation: "ا makes a long vowel: kitaab.", conceptKeys: ["letter:alif"], metadata: { correction: "kitaab" } },
        ],
      },
    ],
  },
  {
    slug: "advanced-marks",
    title: "Advanced Marks",
    description: "Tanween, taa marbuta, hamza, and the definite article.",
    stage: 8,
    lessons: [
      {
        slug: "tanween",
        title: "Tanween ً ٌ ٍ",
        description: "Double vowel marks that add -an, -un, -in.",
        conceptKeys: ["diacritic:tanween_an", "diacritic:tanween_un", "diacritic:tanween_in"],
        exercises: [
          { type: "intro", promptArabic: "ً ٌ ٍ", promptText: "Tanween doubles a vowel mark and adds an n sound:\nً = an\nٌ = un\nٍ = in", correctAnswers: ["continue"], conceptKeys: ["diacritic:tanween_an"] },
          { type: "intro", promptArabic: "كِتَابًا", promptText: "كِتَابًا → kitaaban", correctAnswers: ["continue"], conceptKeys: ["diacritic:tanween_an"] },
          { type: "arabic_to_latin_mc", promptArabic: "بَابًا", correctAnswers: ["baaban"], distractors: ["baaba", "baabun", "baabin"], conceptKeys: ["diacritic:tanween_an"] },
          { type: "arabic_to_latin_mc", promptArabic: "كِتَابٌ", correctAnswers: ["kitaabun"], distractors: ["kitaaban", "kitaabin", "kitaabu"], conceptKeys: ["diacritic:tanween_un"] },
          { type: "arabic_to_latin_mc", promptArabic: "كِتَابٍ", correctAnswers: ["kitaabin"], distractors: ["kitaaban", "kitaabun", "kitaabi"], conceptKeys: ["diacritic:tanween_in"] },
          { type: "type_transliteration", promptArabic: "قَلَمًا", correctAnswers: ["qalaman"], conceptKeys: ["diacritic:tanween_an"] },
          { type: "matching", promptText: "Match tanween", correctAnswers: ["بًا=ban", "بٌ=bun", "بٍ=bin"], options: ["بًا", "بٌ", "بٍ"], tokens: ["ban", "bun", "bin"], conceptKeys: ["diacritic:tanween_an", "diacritic:tanween_un", "diacritic:tanween_in"] },
        ],
      },
      {
        slug: "taa-marbuta-hamza",
        title: "ة and ء",
        description: "Word-final ة and the hamza catch.",
        conceptKeys: ["letter:taa_marbuta", "letter:hamza"],
        exercises: [
          { type: "intro", promptArabic: "ة", promptText: "Taa marbuta (ة) usually sounds like a / ah at the end of a word.", correctAnswers: ["continue"], conceptKeys: ["letter:taa_marbuta"] },
          { type: "intro", promptArabic: "ء", promptText: "Hamza (ء) is a brief catch in the throat. We write it as a stop (often ignored in beginner typing as ').", correctAnswers: ["continue"], conceptKeys: ["letter:hamza"] },
          { type: "type_transliteration", promptArabic: "مَدْرَسَة", correctAnswers: ["madrasa", "madrasah"], conceptKeys: ["letter:taa_marbuta"] },
          { type: "type_transliteration", promptArabic: "شَجَرَة", correctAnswers: ["shajara", "shajarah"], conceptKeys: ["letter:taa_marbuta"] },
          { type: "arabic_to_latin_mc", promptArabic: "مَاء", correctAnswers: ["maa", "maa'"], distractors: ["ma", "mau", "mai"], conceptKeys: ["letter:hamza", "letter:alif"] },
          { type: "type_transliteration", promptArabic: "سَمَاء", correctAnswers: ["samaa", "samaa'"], conceptKeys: ["letter:hamza"] },
          { type: "find_mistake", promptArabic: "مَدْرَسَة", promptLatin: "madrasat", promptText: "Correct at word end?", correctAnswers: ["wrong"], explanation: "At the end, ة is usually a/ah — madrasa — not madrasat.", conceptKeys: ["letter:taa_marbuta"], metadata: { correction: "madrasa" } },
        ],
      },
      {
        slug: "alif-lam",
        title: "The definite article ال",
        description: "Reading al- before sun and moon letters.",
        conceptKeys: ["reading_rule:definite_article", "reading_rule:sun_letters"],
        exercises: [
          { type: "intro", promptArabic: "ال", promptText: "ال at the start often means 'the'. Beginners can read it as al- before many letters.", correctAnswers: ["continue"], conceptKeys: ["reading_rule:definite_article"] },
          { type: "intro", promptArabic: "الشَّمْس", promptText: "Before some letters (sun letters), the ل is absorbed and the next letter doubles:\nالشَّمْس → ash-shams", correctAnswers: ["continue"], conceptKeys: ["reading_rule:sun_letters"] },
          { type: "type_transliteration", promptArabic: "الْكِتَاب", correctAnswers: ["alkitaab", "al-kitaab"], conceptKeys: ["reading_rule:definite_article"] },
          { type: "type_transliteration", promptArabic: "الْقَلَم", correctAnswers: ["alqalam", "al-qalam"], conceptKeys: ["reading_rule:definite_article"] },
          { type: "type_transliteration", promptArabic: "الشَّمْس", correctAnswers: ["ashshams", "ash-shams", "alshams"], conceptKeys: ["reading_rule:sun_letters"] },
          { type: "type_transliteration", promptArabic: "النُّور", correctAnswers: ["annuur", "an-nuur", "alnuur"], conceptKeys: ["reading_rule:sun_letters"] },
          { type: "arabic_to_latin_mc", promptArabic: "الْبَاب", correctAnswers: ["albaab", "al-baab"], distractors: ["abbaab", "baab", "alba"], conceptKeys: ["reading_rule:definite_article"] },
        ],
      },
    ],
  },
  {
    slug: "reduced-vowels",
    title: "Reading Without Full Vowels",
    description: "Gradually drop predictable marks.",
    stage: 9,
    lessons: [
      {
        slug: "drop-predictable",
        title: "Drop Predictable Marks",
        description: "Same words — fewer short vowels shown.",
        xpReward: 25,
        exercises: [
          { type: "intro", promptArabic: "كتاب", promptText: "You've seen كِتَاب. Now try كتاب — use what you already know.", correctAnswers: ["continue"], conceptKeys: ["letter:alif"] },
          { type: "type_transliteration", promptArabic: "كتاب", promptText: "You practiced this vowelled. Decode it.", correctAnswers: ["kitaab"], conceptKeys: ["letter:alif"] },
          { type: "type_transliteration", promptArabic: "قلم", correctAnswers: ["qalam"], conceptKeys: ["letter:qaf"] },
          { type: "type_transliteration", promptArabic: "باب", correctAnswers: ["baab"], conceptKeys: ["letter:alif"] },
          { type: "type_transliteration", promptArabic: "نور", correctAnswers: ["nuur", "nur"], conceptKeys: ["letter:waw"] },
          { type: "build_transliteration", promptArabic: "سلام", correctAnswers: ["salaam"], tokens: ["sa", "laa", "m", "salam", "sala"], conceptKeys: ["letter:alif"] },
          { type: "find_mistake", promptArabic: "كتاب", promptLatin: "katab", promptText: "Likely reading?", correctAnswers: ["wrong"], explanation: "Familiar pattern is kitaab (book shape), not katab.", conceptKeys: ["letter:alif"], metadata: { correction: "kitaab" } },
        ],
      },
      {
        slug: "partially-vowelled",
        title: "Partially Vowelled Text",
        description: "Some helpers remain; decode the rest.",
        xpReward: 25,
        exercises: [
          { type: "type_transliteration", promptArabic: "مَكتب", correctAnswers: ["maktab"], conceptKeys: ["diacritic:sukun"] },
          { type: "type_transliteration", promptArabic: "مَدرسة", correctAnswers: ["madrasa", "madrasah"], conceptKeys: ["letter:taa_marbuta"] },
          { type: "type_transliteration", promptArabic: "كَبير", correctAnswers: ["kabiir", "kabir"], conceptKeys: ["letter:ya"] },
          { type: "type_transliteration", promptArabic: "صَغير", correctAnswers: ["saghiir", "saghir", "ṣaghiir"], conceptKeys: ["letter:sad"] },
          { type: "type_transliteration", promptArabic: "يَكتب", correctAnswers: ["yaktub", "yaktubu"], conceptKeys: ["diacritic:sukun"] },
          { type: "type_transliteration", promptArabic: "الشمس", correctAnswers: ["ashshams", "ash-shams", "alshams"], conceptKeys: ["reading_rule:sun_letters"] },
        ],
      },
      {
        slug: "unvowelled-familiar",
        title: "Familiar Words Unvowelled",
        description: "Only words you've already decoded with vowels.",
        xpReward: 30,
        estimatedMin: 6,
        exercises: [
          { type: "type_transliteration", promptArabic: "كتب", correctAnswers: ["kataba", "kutub", "katab"], explanation: "Common readings: kataba (he wrote) or kutub (books). Either shows you can decode the skeleton.", conceptKeys: ["letter:kaf", "letter:ta", "letter:ba"] },
          { type: "type_transliteration", promptArabic: "درس", correctAnswers: ["darasa", "dars"], conceptKeys: ["letter:dal"] },
          { type: "type_transliteration", promptArabic: "بيت", correctAnswers: ["bayt", "bayit"], conceptKeys: ["letter:ya"] },
          { type: "type_transliteration", promptArabic: "شمس", correctAnswers: ["shams"], conceptKeys: ["letter:shin"] },
          { type: "type_transliteration", promptArabic: "قلم", correctAnswers: ["qalam"], conceptKeys: ["letter:qaf"] },
          { type: "type_transliteration", promptArabic: "طالب", correctAnswers: ["taalib", "talib", "ṭaalib"], conceptKeys: ["letter:ta_emphatic"] },
        ],
      },
    ],
  },
  {
    slug: "challenges",
    title: "Reading Challenges",
    description: "Longer vowelled passages to decode.",
    stage: 10,
    lessons: [
      {
        slug: "phrase-challenge",
        title: "Short Phrase Challenge",
        description: "Decode a short vowelled phrase.",
        xpReward: 35,
        estimatedMin: 7,
        exercises: [
          { type: "intro", promptArabic: "كَتَبَ الطَّالِبُ", promptText: "Decode each word. Spaces separate words — build the full line.", correctAnswers: ["continue"], conceptKeys: ["diacritic:shadda"] },
          { type: "type_transliteration", promptArabic: "كَتَبَ الطَّالِبُ", promptText: "Type the whole phrase (spaces optional)", correctAnswers: ["kataba alttaalibu", "kataba at-taalibu", "kataba attaalibu", "kataba alttalibu"], conceptKeys: ["reading_rule:sun_letters"] },
          { type: "type_transliteration", promptArabic: "قَرَأَ الْكِتَابَ", correctAnswers: ["qaraa alkitaaba", "qara'a alkitaaba", "qaraa al-kitaaba"], conceptKeys: ["letter:hamza"] },
          { type: "type_transliteration", promptArabic: "هَذَا بَيْتٌ كَبِيرٌ", correctAnswers: ["hadhaa baytun kabiirun", "hadha baytun kabirun", "haadhaa baytun kabiirun"], conceptKeys: ["letter:dhal"] },
          { type: "build_transliteration", promptArabic: "شَمْسُ النَّهَارِ", correctAnswers: ["shamsu annahaari", "shamsu an-nahaari"], tokens: ["shamsu", "anna", "haari", "shams", "al", "nahar"], conceptKeys: ["reading_rule:sun_letters"] },
          { type: "find_mistake", promptArabic: "هَذَا كِتَابٌ", promptLatin: "hada kitabun", promptText: "Correct?", correctAnswers: ["wrong"], explanation: "ذ = dh and ا lengthens: hadhaa kitaabun.", conceptKeys: ["letter:dhal", "letter:alif"], metadata: { correction: "hadhaa kitaabun" } },
        ],
      },
      {
        slug: "passage-challenge",
        title: "Passage Challenge",
        description: "A longer vowelled line — section by section.",
        xpReward: 40,
        estimatedMin: 7,
        exercises: [
          { type: "type_transliteration", promptArabic: "ذَهَبَ الْوَلَدُ", correctAnswers: ["dhahaba alwaladu", "dhahaba al-waladu"], conceptKeys: ["letter:dhal"] },
          { type: "type_transliteration", promptArabic: "إِلَى الْمَدْرَسَةِ", correctAnswers: ["ilaa almadrasati", "ila al-madrasati", "ilaa almadrasati"], conceptKeys: ["letter:taa_marbuta"] },
          { type: "type_transliteration", promptArabic: "فِي الصَّبَاحِ", correctAnswers: ["fii assabaahi", "fi as-sabaahi", "fii assabah"], conceptKeys: ["reading_rule:sun_letters"] },
          { type: "type_transliteration", promptArabic: "وَقَرَأَ دَرْسَهُ", correctAnswers: ["waqaraa darsahu", "wa qaraa darsahu", "waqara'a darsahu"], conceptKeys: ["letter:hamza"] },
          { type: "type_transliteration", promptArabic: "ثُمَّ كَتَبَ فِي دَفْتَرِهِ", correctAnswers: ["thumma kataba fii daftarihi", "thumma kataba fi daftarihi"], conceptKeys: ["diacritic:shadda"] },
          { type: "type_transliteration", promptArabic: "ذَهَبَ الْوَلَدُ إِلَى الْمَدْرَسَةِ", promptText: "Full line", correctAnswers: ["dhahaba alwaladu ilaa almadrasati", "dhahaba al-waladu ila al-madrasati", "dhahaba alwaladu ilaa almadrasati"], conceptKeys: ["letter:dhal", "letter:taa_marbuta"] },
        ],
      },
      {
        slug: "final-reading-test",
        title: "Final Reading Test",
        description: "Prove you can decode unfamiliar vowelled Arabic.",
        xpReward: 50,
        estimatedMin: 7,
        exercises: [
          { type: "type_transliteration", promptArabic: "يَلْعَبُ الأَطْفَالُ", correctAnswers: ["yalabu alatfaalu", "yal'abu al-atfaalu", "yalabu alatfalu", "yalabu al-atfaalu"], conceptKeys: ["diacritic:sukun"] },
          { type: "type_transliteration", promptArabic: "فِي الْحَدِيقَةِ", correctAnswers: ["fii alhadiiqati", "fi al-hadiqati", "fii alhadiqati"], conceptKeys: ["letter:alif"] },
          { type: "type_transliteration", promptArabic: "تَحْتَ الشَّجَرَةِ", correctAnswers: ["tahta ashshajarati", "tahta ash-shajarati"], conceptKeys: ["reading_rule:sun_letters"] },
          { type: "type_transliteration", promptArabic: "وَيَشْرَبُونَ الْمَاءَ", correctAnswers: ["wayashrabuuna almaa", "wa yashrabuna al-maa", "wayashrabuuna almaa'a"], conceptKeys: ["letter:hamza"] },
          { type: "type_transliteration", promptArabic: "بَعْدَ اللَّعِبِ", correctAnswers: ["bada allaibi", "ba'da al-laibi", "bada allaebi", "baada allaeibi"], conceptKeys: ["diacritic:shadda"] },
          { type: "type_transliteration", promptArabic: "هَذَا دَرْسٌ مُفِيدٌ", correctAnswers: ["hadhaa darsun mufiidun", "hadha darsun mufidun", "haadhaa darsun mufiidun"], conceptKeys: ["letter:dhal"] },
        ],
      },
    ],
  },
];
